In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("/content/data scincare.csv", sep=";")
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print (x)

[['Somethinc Serum' 22.0 50.0]
 ['Wardah Day Cream' nan 30.0]
 ['MS Glow Day Cream' 28.0 80.0]
 ['Wardah Day Cream' 24.0 35.0]
 ['Wardah Day Cream' 19.0 15.0]
 ['Hanasui Serum' nan 20.0]
 ['MS Glow Day Cream' 21.0 50.0]
 ['Somethinc  Serum' 20.0 nan]
 ['Hanasui Serum' 26.0 35.0]
 ['MS Glow Day Cream' 25.0 40.0]
 ['Hanasui Serum' nan 35.0]
 ['MS Glow Day Cream' 29.0 75.0]
 ['Hanasui Serum' 15.0 45.0]
 ['Wardah Day Cream' 20.0 35.0]]


In [4]:
print (y)

['ya' 'ya' 'tidak' 'ya' 'ya' 'ya' 'tidak' 'tidak' 'tidak' 'ya' 'ya'
 'tidak' 'ya' 'ya']


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:2])
x[:, 1:2] = imputer.fit_transform(x[:, 1:2])

In [6]:
print (x)

[['Somethinc Serum' 22.0 50.0]
 ['Wardah Day Cream' 22.636363636363637 30.0]
 ['MS Glow Day Cream' 28.0 80.0]
 ['Wardah Day Cream' 24.0 35.0]
 ['Wardah Day Cream' 19.0 15.0]
 ['Hanasui Serum' 22.636363636363637 20.0]
 ['MS Glow Day Cream' 21.0 50.0]
 ['Somethinc  Serum' 20.0 nan]
 ['Hanasui Serum' 26.0 35.0]
 ['MS Glow Day Cream' 25.0 40.0]
 ['Hanasui Serum' 22.636363636363637 35.0]
 ['MS Glow Day Cream' 29.0 75.0]
 ['Hanasui Serum' 15.0 45.0]
 ['Wardah Day Cream' 20.0 35.0]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [8]:
print (x)

[[0.0 0.0 0.0 1.0 0.0 22.0 50.0]
 [0.0 0.0 0.0 0.0 1.0 22.636363636363637 30.0]
 [0.0 1.0 0.0 0.0 0.0 28.0 80.0]
 [0.0 0.0 0.0 0.0 1.0 24.0 35.0]
 [0.0 0.0 0.0 0.0 1.0 19.0 15.0]
 [1.0 0.0 0.0 0.0 0.0 22.636363636363637 20.0]
 [0.0 1.0 0.0 0.0 0.0 21.0 50.0]
 [0.0 0.0 1.0 0.0 0.0 20.0 nan]
 [1.0 0.0 0.0 0.0 0.0 26.0 35.0]
 [0.0 1.0 0.0 0.0 0.0 25.0 40.0]
 [1.0 0.0 0.0 0.0 0.0 22.636363636363637 35.0]
 [0.0 1.0 0.0 0.0 0.0 29.0 75.0]
 [1.0 0.0 0.0 0.0 0.0 15.0 45.0]
 [0.0 0.0 0.0 0.0 1.0 20.0 35.0]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print (y)

[1 1 0 1 1 1 0 0 0 1 1 0 1 1]


In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [12]:
print (x_train)

[[0.0 1.0 0.0 0.0 0.0 28.0 80.0]
 [1.0 0.0 0.0 0.0 0.0 22.636363636363637 35.0]
 [0.0 0.0 0.0 0.0 1.0 19.0 15.0]
 [0.0 0.0 0.0 0.0 1.0 22.636363636363637 30.0]
 [1.0 0.0 0.0 0.0 0.0 15.0 45.0]
 [0.0 0.0 0.0 1.0 0.0 22.0 50.0]
 [0.0 0.0 0.0 0.0 1.0 20.0 35.0]
 [0.0 1.0 0.0 0.0 0.0 25.0 40.0]
 [1.0 0.0 0.0 0.0 0.0 26.0 35.0]
 [0.0 1.0 0.0 0.0 0.0 29.0 75.0]
 [1.0 0.0 0.0 0.0 0.0 22.636363636363637 20.0]]


In [13]:
print(x_test)

[[0.0 0.0 0.0 0.0 1.0 24.0 35.0]
 [0.0 0.0 1.0 0.0 0.0 20.0 nan]
 [0.0 1.0 0.0 0.0 0.0 21.0 50.0]]


In [14]:
print(y_train)

[0 1 1 1 1 1 1 1 0 0 1]


In [15]:
print (y_test)

[1 0 0]


In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,3:]=sc.fit_transform(x_train[:,3:])
x_test[:,3:]=sc.transform(x_test[:,3:])

In [17]:
print (x_train)

[[0.0 1.0 0.0 -0.316227766016838 -0.6123724356957945 1.3194488156664337
  1.9744220778335273]
 [1.0 0.0 0.0 -0.316227766016838 -0.6123724356957945 -0.0684317051885344
  -0.3525753710417014]
 [0.0 0.0 0.0 -0.316227766016838 1.632993161855452 -1.0093676515308858
  -1.3867964594306919]
 [0.0 0.0 0.0 -0.316227766016838 1.632993161855452 -0.0684317051885344
  -0.611130643138949]
 [1.0 0.0 0.0 -0.316227766016838 -0.6123724356957945 -2.044397192507472
  0.16453517315279384]
 [0.0 0.0 0.0 3.16227766016838 -0.6123724356957945 -0.23309549579844596
  0.42309044525004147]
 [0.0 0.0 0.0 -0.316227766016838 1.632993161855452 -0.7506102662867392
  -0.3525753710417014]
 [0.0 1.0 0.0 -0.316227766016838 -0.6123724356957945 0.5431766599339938
  -0.09402009894445379]
 [1.0 0.0 0.0 -0.316227766016838 -0.6123724356957945 0.8019340451781404
  -0.3525753710417014]
 [0.0 1.0 0.0 -0.316227766016838 -0.6123724356957945 1.5782062009105802
  1.7158668057362796]
 [1.0 0.0 0.0 -0.316227766016838 -0.6123724356957945 -

In [18]:
print (x_test)

[[0.0 0.0 0.0 -0.316227766016838 1.632993161855452 0.28441927468984723
  -0.3525753710417014]
 [0.0 0.0 1.0 -0.316227766016838 -0.6123724356957945 -0.7506102662867392
  nan]
 [0.0 1.0 0.0 -0.316227766016838 -0.6123724356957945 -0.49185288104259256
  0.42309044525004147]]
